### ISSUE TITLE
Collection of issues

### ISSUE THREAD

**Issue by greggersh** [nmudd-cms/wnmg-xlc#1]
- HTTP (not HTML) verbs
- Should also specify use of HTTP status codes to indicate response success/failure
- JSON does not use underscore by default, in fact many Google JSON APIs use camel case. I'm fine with standardizing on one or the other, but it's not the case that one is preferred by JSON.
- API should use CDN where applicable (in some cases, caching via CDN will not work or will be detrimental).
- What does 'API is designed to accommodate future and currently unknown business requirements.' mean? I would argue that the API should be designed to meet current business requirements, and good versioning allows us to support new requirements in the future.
- Should always use HTTPS.
- 'API supports an unlimited number of clients.' Scales infinitely? I guess, although there's always going to be some theoretical limit.  I would prefer we say something about SLA and response times being well-defined and reasonable.

**Comment by nmudd-cms** [comment]
I made changes based on your feedback. Thanks! @greggersh
